---
apiVersion: v1
kind: Namespace
metadata:
  name: covoit

---
apiVersion: v1
kind: Secret
metadata:
  name: covoit-secrets
  namespace: covoit
type: Opaque
stringData:
  api-gateway-secret: "your-secret-key-change-in-production"
  auth-secret: "your-secret-key-auth-service-change-in-production"
  auth-db-url: "postgresql://postgres:postgres@postgres-auth.default.svc.cluster.local:5432/auth_db"
  user-db-url: "postgresql://postgres:postgres@postgres-user.default.svc.cluster.local:5432/user_db"
  redis-url: "redis://redis.default.svc.cluster.local:6379"
  rabbitmq-url: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/"
